/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobileinventory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author POOJA KUMARI
 */
public class huawei extends javax.swing.JFrame {

    /**
     * Creates new form huawei
     */
  
    
    public huawei() {
        initComponents();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        huaweiTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        honor10Btn = new javax.swing.JButton();
        honor8Btn = new javax.swing.JButton();
        p9Btn = new javax.swing.JButton();
        nexus6PBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(3, 78, 162));

        jPanel1.setBackground(new java.awt.Color(168, 9, 9));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(225, 190, 231));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 40));

        honor10Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/honor10.jpg"))); // NOI18N
        honor10Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                honor10BtnActionPerformed(evt);
            }
        });
        jPanel1.add(honor10Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 57, 1230, 630));

        honor8Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/honor8(2).jpg"))); // NOI18N
        honor8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                honor8BtnActionPerformed(evt);
            }
        });
        jPanel1.add(honor8Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 710, 1230, 630));

        p9Btn.setBackground(new java.awt.Color(255, 255, 255));
        p9Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/p9.jpg"))); // NOI18N
        p9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p9BtnActionPerformed(evt);
            }
        });
        jPanel1.add(p9Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 1350, 1230, 630));

        nexus6PBtn.setBackground(new java.awt.Color(255, 255, 255));
        nexus6PBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/nexus6p.jpg"))); // NOI18N
        nexus6PBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nexus6PBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nexus6PBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 2000, 1230, 630));

        jScrollPane1.setViewportView(jPanel1);

        huaweiTabbedPane.addTab("Huawei", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(huaweiTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(huaweiTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        huaweiTabbedPane.getAccessibleContext().setAccessibleName("iPhone");

        setSize(new java.awt.Dimension(1395, 796));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void honor10BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_honor10BtnActionPerformed
        // TODO add your handling code here:

   honor10 h10 = new honor10();
     h10.setName("Honor 10");
     huaweiTabbedPane.add(h10);
    
      
    }//GEN-LAST:event_honor10BtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
this.setVisible(false);
mobInventoryFrame mi =new mobInventoryFrame();
mi.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void honor8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_honor8BtnActionPerformed
//        // TODO add your handling code here:
 honor8 h8 = new honor8();
     h8.setName("Honor 8");
     huaweiTabbedPane.add(h8);
    }//GEN-LAST:event_honor8BtnActionPerformed

    private void p9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p9BtnActionPerformed
      // TODO add your handling code here:
     huaweiP9 p9  = new huaweiP9();
     p9.setName("Huawei P9");
     huaweiTabbedPane.add(p9);
    }//GEN-LAST:event_p9BtnActionPerformed

    private void nexus6PBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nexus6PBtnActionPerformed
        // TODO add your handling code here:
 GoogleNexus6P gn6p = new GoogleNexus6P();
      gn6p.setName("GoogleNexus 6P");
      huaweiTabbedPane.add(gn6p);
    }//GEN-LAST:event_nexus6PBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(huawei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(huawei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(huawei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(huawei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new huawei().show();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton honor10Btn;
    private javax.swing.JButton honor8Btn;
    public javax.swing.JTabbedPane huaweiTabbedPane;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nexus6PBtn;
    private javax.swing.JButton p9Btn;
    // End of variables declaration//GEN-END:variables
}
