/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobileinventory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author POOJA KUMARI
 */
public class iPhone extends javax.swing.JFrame {

    /**
     * Creates new form iPhone
     */
  
    
    public iPhone() {
        initComponents();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iPhoneTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        iphoneXBtn = new javax.swing.JButton();
        iphone8pbtn = new javax.swing.JButton();
        iphoneSEBtn = new javax.swing.JButton();
        iphone6SBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(3, 78, 162));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(225, 190, 231));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 40));

        iphoneXBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/iphonex.jpg"))); // NOI18N
        iphoneXBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iphoneXBtnActionPerformed(evt);
            }
        });
        jPanel1.add(iphoneXBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 57, 1230, 630));

        iphone8pbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/iphone8p.jpg"))); // NOI18N
        iphone8pbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iphone8pbtnActionPerformed(evt);
            }
        });
        jPanel1.add(iphone8pbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 710, 1230, 630));

        iphoneSEBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/iphone_se.jpg"))); // NOI18N
        iphoneSEBtn.setText("jButton1");
        iphoneSEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iphoneSEBtnActionPerformed(evt);
            }
        });
        jPanel1.add(iphoneSEBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 1350, 1230, 630));

        iphone6SBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/iphone-6s.jpg"))); // NOI18N
        iphone6SBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iphone6SBtnActionPerformed(evt);
            }
        });
        jPanel1.add(iphone6SBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 2000, 1230, 630));

        jScrollPane1.setViewportView(jPanel1);

        iPhoneTabbedPane.addTab("iPhone", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iPhoneTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iPhoneTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        iPhoneTabbedPane.getAccessibleContext().setAccessibleName("iPhone");

        setSize(new java.awt.Dimension(1395, 796));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iphoneXBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iphoneXBtnActionPerformed
        // TODO add your handling code here:

   iPhoneX ix = new iPhoneX();
     ix.setName("iPhone X");
     iPhoneTabbedPane.add(ix);
    
      
    }//GEN-LAST:event_iphoneXBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
this.setVisible(false);
mobInventoryFrame mi =new mobInventoryFrame();
mi.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void iphone8pbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iphone8pbtnActionPerformed
//        // TODO add your handling code here:

       iPhone8P i8p = new iPhone8P();
      i8p.setName("iPhone 8 Plus");
      iPhoneTabbedPane.add(i8p);
    }//GEN-LAST:event_iphone8pbtnActionPerformed

    private void iphoneSEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iphoneSEBtnActionPerformed
      // TODO add your handling code here:
     iPhoneSE ise = new iPhoneSE();
      ise.setName("iPhone SE");
      iPhoneTabbedPane.add(ise);
    }//GEN-LAST:event_iphoneSEBtnActionPerformed

    private void iphone6SBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iphone6SBtnActionPerformed
        // TODO add your handling code here:
  iPhone6S i6s = new iPhone6S();
      i6s.setName("iPhone 6S");
      iPhoneTabbedPane.add(i6s);
    }//GEN-LAST:event_iphone6SBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new iPhone().show();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane iPhoneTabbedPane;
    private javax.swing.JButton iphone6SBtn;
    private javax.swing.JButton iphone8pbtn;
    private javax.swing.JButton iphoneSEBtn;
    public javax.swing.JButton iphoneXBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
