/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobileinventory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author POOJA KUMARI
 */
public class samsung extends javax.swing.JFrame {

    /**
     * Creates new form samsung
     */
  
    
    public samsung() {
        initComponents();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SamsungTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        s9Btn = new javax.swing.JButton();
        on7Btn = new javax.swing.JButton();
        note8 = new javax.swing.JButton();
        s6Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(3, 78, 162));

        jPanel1.setBackground(new java.awt.Color(3, 78, 162));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(225, 190, 231));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 40));

        s9Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/s9.jpg"))); // NOI18N
        s9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s9BtnActionPerformed(evt);
            }
        });
        jPanel1.add(s9Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 57, 1230, 630));

        on7Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/on7.jpg"))); // NOI18N
        on7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on7BtnActionPerformed(evt);
            }
        });
        jPanel1.add(on7Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 710, 1230, 630));

        note8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/note8.jpg"))); // NOI18N
        note8.setText("jButton1");
        note8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                note8ActionPerformed(evt);
            }
        });
        jPanel1.add(note8, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 1350, 1230, 630));

        s6Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileinventory/s6Edge.jpg"))); // NOI18N
        s6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6BtnActionPerformed(evt);
            }
        });
        jPanel1.add(s6Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 2000, 1230, 630));

        jScrollPane1.setViewportView(jPanel1);

        SamsungTabbedPane.addTab("SAMSUNG", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SamsungTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SamsungTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1395, 796));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void s9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s9BtnActionPerformed
        // TODO add your handling code here:

        GalaxyS9 s9 = new GalaxyS9();
      s9.setName("GalaxyS9");
      SamsungTabbedPane.add(s9);
    
      
    }//GEN-LAST:event_s9BtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
this.setVisible(false);
mobInventoryFrame mi =new mobInventoryFrame();
mi.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void on7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on7BtnActionPerformed
        // TODO add your handling code here:

        On7Prime on7 = new On7Prime();
      on7.setName("GalaxyOn7Prime");
      SamsungTabbedPane.add(on7);
    }//GEN-LAST:event_on7BtnActionPerformed

    private void note8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_note8ActionPerformed
      // TODO add your handling code here:
      GalaxyNote8 note8 = new GalaxyNote8();
      note8.setName("Galaxy Note 8");
      SamsungTabbedPane.add(note8);
    }//GEN-LAST:event_note8ActionPerformed

    private void s6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6BtnActionPerformed
        // TODO add your handling code here:
        GalaxyS6Edge EdgeP = new GalaxyS6Edge();
      EdgeP.setName("Galaxy S6 Edge+");
      SamsungTabbedPane.add(EdgeP);
    }//GEN-LAST:event_s6BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(samsung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(samsung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(samsung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(samsung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new samsung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane SamsungTabbedPane;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton note8;
    private javax.swing.JButton on7Btn;
    private javax.swing.JButton s6Btn;
    public javax.swing.JButton s9Btn;
    // End of variables declaration//GEN-END:variables
}
