/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

/**
 *
 * @author POOJA KUMARI
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class ADD extends javax.swing.JInternalFrame  {

    /**
     * Creates new form ADD
     */
    Connection con;
    Statement st;
    ResultSet rs;
    
    public static String S_Name , Price , No_of_Items, Item ;
     boolean insert=false;
    public void emptyFields(){
    
 sNameField.setText("");
 priceField.setText("");
 noOfItemsField.setText("");
 
    }
    
    public void insertData(String Item,String S_Name,int Price){
       
    
 //System.out.println(S_Name +Price +No_of_Items+ Item );
 
 //    inserting into database
 try{
        int result = st.executeUpdate("INSERT INTO ITEMS(NAME, SUPPNAME, PRICE) VALUES('" +Item+"','" +S_Name+"','" +Price+"') ");
                      if(result==1){
              insert = true;
              }
                      else{
                          insert = false;
              }


}catch(Exception e){
        e.printStackTrace();
        }}
    
    public ADD() {
        initComponents();
     //Combobox items
        selectItem.addItem("Keyboard");
        selectItem.addItem("Mouse");
        selectItem.addItem("Monitor");
        selectItem.addItem("VGA Cables");
        selectItem.addItem("Graphic Card");
        selectItem.addItem("LCD");
        selectItem.addItem("Laptop");
        
    //connection to database
      try{
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
 con=DriverManager.getConnection ("jdbc:oracle:thin:@localhost:1521:XE","Computershop","null");
            if(con!=null){
         //   System.out.println("connection ");
            }
             st = con.createStatement();
                
              rs = st.executeQuery("SELECT * FROM ITEMS ");
while(rs.next())                    //Continue block of code
{
String name = rs.getString("NAME");
String roll = rs.getString("SUPPNAME");
//System.out.println("name "+name+" roll number "+roll);
    	}

             


        }catch(Exception e){
        e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        noOfItemsField = new javax.swing.JTextField();
        selectItem = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 550, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUPPLIER NAME : ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 220, 30));

        sNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(sNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 310, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRICE                     :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 220, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NO OF ITEMS       :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, 30));

        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });
        jPanel2.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 310, 30));

        noOfItemsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfItemsFieldActionPerformed(evt);
            }
        });
        jPanel2.add(noOfItemsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 310, 30));

        selectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectItemActionPerformed(evt);
            }
        });
        jPanel2.add(selectItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 310, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SELECT ITEM      :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 210, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 110, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 550, 10));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 550, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 550, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNameFieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void noOfItemsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfItemsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfItemsFieldActionPerformed

    private void selectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
S_Name = sNameField.getText().toString();
Price = priceField.getText();
 No_of_Items = noOfItemsField.getText().toString();
 Item      = selectItem.getSelectedItem().toString();
if(S_Name==null || Price==null || No_of_Items==null){
    JOptionPane.showMessageDialog(null,"PLEASE! ENTER ALL REQUIREMENTS");

    } else{
 //insert into database
 for(int i=1;i<=Integer.parseInt(No_of_Items);i++){
     insertData(Item,S_Name,Integer.parseInt(Price));
 }
 if(insert){
     JOptionPane.showMessageDialog(null,"Data Inserted");
 }else{
     JOptionPane.showMessageDialog(null,"Not Inserted");
 }
 //set all fields to initial condition
 emptyFields();
    }//GEN-LAST:event_jButton1ActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField noOfItemsField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField sNameField;
    private javax.swing.JComboBox<String> selectItem;
    // End of variables declaration//GEN-END:variables
}
